##################################################################################################
# Dev Tools service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: dev-tools
  labels:
    app: dev-tools
    service: dev-tools
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: dev-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-tools
  labels:
    app: dev-tools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-tools
  template:
    metadata:
      labels:
        app: dev-tools
        version: 1.1.0
    spec:
      containers:
      - name: dev-tools
        image: dev-tools:1.1.0
        ports:
        - containerPort: 8080
